networks:
  def_netw:
    driver: bridge

services:
  bot_app:
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - def_netw